# Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry_db
spring.datasource.username=postgres
spring.datasource.password=MagnusChase05!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and State Validations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.sql.init.mode=always

# Enable Flyway
spring.flyway.enabled=true
